# Generated by Django 4.2.2 on 2023-06-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handyman', '0001_initial'),
        ('client', '0001_initial'),
        ('users', '0009_remove_location_client_remove_location_handyman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handyman.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='handyman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.handyman'),
        ),
        migrations.AddField(
            model_name='booking',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_request_booking', to='client.jobrequest'),
        ),
    ]
