# Generated by Django 4.2.2 on 2023-06-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='handyman',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='job_request',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='handyman',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='service',
        ),
    ]
