# Generated by Django 4.2.2 on 2023-06-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0009_remove_location_client_remove_location_handyman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('Movers', 'Movers'), ('TV & Internet', 'TV & Internet'), ('plumbing', 'Plumbing'), ('Electrician', 'Electrician'), ('Dry cleaning', 'Dry cleaning')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.booking')),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.handyman')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField()),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.handymanprofile')),
            ],
        ),
    ]
